### PR TITLE
info window 레이아웃 수정

### LINKED ISSUE #112: FE 미리보기 배포 기능을 추가한다
### ✨ Describe

FE 디렉토리에 `preview ` 키워드를 포함한 커밋 메시지가 push 되면 작동해 
`preview.dailyroad.site ` 서브도메인에 배포

### ✅ Tasks

- [x] nginx 설정 수정
- [x] 배포 깃허브 액션 추가

### 🕰️ Estimated Time of Completion

1H

### 🙋🏻 More

_No response_

### PR DESCRIPTION
**Pull request by 1119wj**
#preview

## 📄 Summary

>info window 레이아웃 수정

## 🙋🏻 More

>

### 🕰️ Actual Time of Completion

>

close #112

### CODE REVIEW

**Comment by Miensoap** [comment]
image

**Comment by hyohyo12** [comment]
image

**Comment by Miensoap** [comment]
image

**Comment by hyohyo12** [comment]
image

**Review by Miensoap — APPROVED** [review]

**Pull request merged**
